laravel/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::resource('movie','MovieController');
Route::get('movie/destroy/{id}',['as'=>'movie/destroy','uses'=>'MovieController@destroy']);
Route::post('movie/search',['as'=>'movie/search','uses'=>'MovieController@search']);



Route::get('/', function () {
    return view('welcome');
});

laravel/app/Models/Movie.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;

class Movie extends Model
{
    protected $table = 'movies';
    protected $fillable = ['name','description'];
    protected $guarded = ['id'];

    
public function store(Request $Request)
{
	$movie = new Movie;
	$movie->create($request->all());
	return redirect('movie');
}
}
/*
public function store(Request $Request)
{
	$movie = new Movie;
	$movie->name = $request->name;
	$movie->description = $request->description;
	$movie->save();
	return redirect('movie');


}*/

laravel/app/User.php
<?php

namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements AuthenticatableContract, CanResetPasswordContract
{
    use Authenticatable, CanResetPassword;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'email', 'password'];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['password', 'remember_token'];
}

laravel/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;

abstract class Controller extends BaseController
{
    use DispatchesJobs, ValidatesRequests;
}

laravel/app/Http/Controllers/MovieController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Movie as Movie;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class MovieController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $movies = Movie::all();
        return \View::make('list',compact('movies'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return \View::make('new');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }
}

laravel/resources/views/list.blade.php
@extends('app')
@section('content')
<div class="container">
	<div class="row">
		{!! Form::open(['route' => 'movie/search','method' => 'post','novalidate','class' => 'form-inline'])!!}
		<div class="form-group">
			<label for="exampleInputName2">Name</label>
			<input type="text" class="form-control" name="name">
		</div>
		<button type="submit" class="btn btn-default">Search</button>
		<a href="{{route('movie.index')}}" class="btn btn-primary">All</a>
		<a href="{{route('movie.create')}}" class="btn btn-primary">Create</a>
		{!! Form::close()!!}
		<br>
			<table class="table table-condensed table-striped table-bordered">
		<thead>
			<tr>
				<th>Name</th>
				<th>Description</th>
				<th>Action</th>
			</tr>
		</thead>
		<tbody>
			@forearch($movies as $movie)
			<tr>
				<td>{{$movie->name}}</td>
				<td>{{$movie->description}}</td>
				<td>
					<a class="btn btn-primary btn-xs" href="{{route('movie.edit',['id'=> $movie->id])}}"> Edit </a>
					<a class="btn btn-danger btn-xs" href="{{rout('movie/destroy',['id'=> &movie->id])}}"> Delete</a>
				</td>
			</tr>
			@endforeach
		</tbody>
			</table>
	</div>
</div>
@endsection

laravel/resources/views/new.blade.php
@extends('app')
@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			{!! Form::open(['route' => 'movie.store','method' => 'post','novalidate'])!!}
		<div class="form-group">
			{!! Form::label('full_name','Nombre')!!}
			{!! Form::text('name',null,['class' => 'form-control','required' => 'required'])!!}
		</div>
		<div class="form-group">
			{!! Form::label('email','Descripci&oacute;n')!!}
			{!! Form::text('description',null,['class' => 'form-control','required' => 'required'])!!}
		</div>
		<div class="form-group">
			{!! Form::submit('Enviar',['class' => 'btn btn-sucess'])!!}
		</div>
		{!! Form::close()!!}
	</div>
</div>
@endsection